# Generated by Django 4.2.6 on 2023-10-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skill_language_skill_level_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='language',
            field=models.CharField(choices=[('C++', 'Cpp'), ('javascript', 'Javascript'), ('python', 'Python'), ('java', 'Java'), ('lua', 'Lua'), ('rust', 'Rust'), ('go', 'Go'), ('julia', 'Julia')], default='python', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('experienced', 'Experienced'), ('expert', 'Expert')], default='beginner', max_length=255),
        ),
    ]
